on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: "Tag to create, format OC_MAJOR.x-YYYY-MM-DD cf 17.x-2025-04-24"
        required: true

name: Create release tag

jobs:
  build:
    name: Create release tag
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: prepare git
        run: |
          git config --global user.email 'cloud@opencast.org'
          git config --global user.name 'Release Bot'

      - name: tag and push
        run: |
          git tag ${{ inputs.tag }}
          git push origin ${{ inputs.tag }}
