on:
  workflow_dispatch:
  push:
    tags:
      # CF: 17.x-YYYY-MM-DD
      - '*.x-*-*-*'

name: Create release draft
jobs:
  build:
    name: Create release from tag
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: use node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: download dependencies
        run: npm ci

      - name: create release tarball
        run: ./.github/build-release.sh

      - name: create new release
        uses: softprops/action-gh-release@v2
        with:
          files: oc-editor-*.tar.gz
          fail_on_unmatched_files: true
          generate_release_notes: true
