on:
  workflow_dispatch:
  push:
    tags:
      # CF: 17.x-YYYY-MM-DD
      - '*.x-*-*-*'

name: Create release
jobs:
  build:
    name: Create release from tag
    if: github.repository_owner == 'opencast'
    runs-on: ubuntu-latest
    permissions:
      contents: write #for the release
      pull-requests: write #For the PR in the upstream repo

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: use node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: download dependencies
        run: npm ci

      - name: build release
        env:
          PUBLIC_URL: /editor-ui
          VITE_APP_SETTINGS_PATH: /ui/config/editor/editor-settings.toml
        run: npm run build

      - name: create release tarball
        working-directory: build
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tar -czf "../oc-editor-$(git describe --tags).tar.gz" *
          echo EDITOR_CHECKSUM=`sha256sum ../oc-editor-$(git describe --tags).tar.gz | cut -f 1 -d " "` >> $GITHUB_ENV
          echo EDITOR_TAG=$(git describe --tags) >> $GITHUB_ENV
          while read branchname
          do
            #branchname looks like 'develop' or 'r/17.x', the describe + cut looks like '17.x', so we prefix with r/
            # NB: branchname == develop *should not match* anything so that we fall back to the if case below
            if [ "$branchname" != "r/`git describe --tags | cut -f 1 -d -`" ]; then
              continue
            fi
            echo "Base branch is $branchname"
            BASE_BRANCH="$branchname"
            echo "BASE_BRANCH=$branchname" >> $GITHUB_ENV
            break
          done <<< `gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/opencast/opencast/branches?per_page=100 | \
            jq -r '. | map(select(.name | match("r/[0-9]*.x|develop"))) | .[].name'`
          if [ -z "${BASE_BRANCH}" ]; then
            echo "Base branch is develop"
            echo "BASE_BRANCH=develop" >> $GITHUB_ENV
          fi

      - name: create new release
        uses: softprops/action-gh-release@v2
        with:
          files: oc-editor-*.tar.gz
          fail_on_unmatched_files: true
          generate_release_notes: true

      - name: Prepare git
        run: |
          git config --global user.name "Release Bot"
          git config --global user.email "cloud@opencast.org"

      - name: Prepare GitHub SSH key
        env:
          DEPLOY_KEY: ${{ secrets.MODULE_PR_DEPLOY_KEY }}
        run: |
          install -dm 700 ~/.ssh/
          echo "${DEPLOY_KEY}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone upstream repository
        run: |
          git clone -b $BASE_BRANCH "git@github.com:opencast/opencast.git" ~/opencast
          cd ~/opencast
          git checkout -b t/editor-$EDITOR_TAG

      - name: Update the editor pom file
        run: |
          cd ~/opencast
          sed -i "s#<editor.sha256>.*</editor.sha256>#<editor.sha256>$EDITOR_CHECKSUM</editor.sha256>#" modules/editor/pom.xml
          sed -i "s#<editor.url>.*</editor.url>#<editor.url>https://github.com/opencast/opencast-editor/releases/download/$EDITOR_TAG/oc-editor-$EDITOR_TAG.tar.gz</editor.url>#" modules/editor/pom.xml
          git add modules/editor/pom.xml
          git commit -m "Updating editor to $EDITOR_TAG"
          git push origin t/editor-$EDITOR_TAG
          #This token is an account wide token which allows creation of PRs and pushes.
          echo "${{ secrets.MODULE_PR_TOKEN }}" > token.txt
          gh auth login --with-token < token.txt
          gh pr create \
            --title "Update $BASE_BRANCH Editor to $EDITOR_TAG" \
            --label editor --label maintenance \
            --body "Updating Opencast $BASE_BRANCH Editor module to [$EDITOR_TAG](https://github.com/opencast/opencast-editor/releases/tag/$EDITOR_TAG)" \
            --head=opencast:t/editor-$EDITOR_TAG \
            --base $BASE_BRANCH \
            -R opencast/opencast
